---
- hosts: all
  become: yes
  tasks:

    - name: Remove java old version
      package:
        name: java-1.7.0-openjdk
        state: absent

    - name: Install supported java version
      package:
        name: java-1.8.0-openjdk
        state: present

    - name: Jenkins add repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d

    - name: Import jenkins GPG key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key

    - name: Install jenkins
      package:
        name: jenkins
        enablerepo: jenkins 
        state: latest 

    - name: Jenkins service start
      service: 
        name: jenkins
        enabled: yes
        state: started

