---
- hosts: all
  become: yes
  tasks:
    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items: 
        - httpd
        - gcc
        - git
        - httpd-devel
