---
- hosts: all
  become: yes 
  
  vars:
    packages:
      - httpd
      - wget
      - gcc
      - git

  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
   
    
